.type Context
.type AllocationContext

//Since the constructors do not have parameters to initiallize a record, I use the $ sign.


.decl context(?ctx:Context)
.decl alloc_context(?aCtx:AllocationContext)


.decl context_new(?ctx:Context)
.decl alloc_context_new(?aCtx:AllocationContext)

context_new(?ctx) :-
   ?ctx = "*emptyContext*"

alloc_context_new(?aCtx) :-
   ?aCtx = "*emptyAllocContext*".
